# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7002f9b29426f0b9c7ef0064e8ddb24cec0198124dd63d400f8c437842bb511f9a8a605508364ffdc8bbee16f20e125a1cd337cdcaa61c681574e940c9add2e

test:
  secret_key_base: 95978d3a65c94e73e96d6c5bef9c00d0a39f217b363ed668de94a34b08279e1046c7f7d402acb145bfae7fc1a977c9e672d4009987dd913cf7023baaefcffb90

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
